sudo: false
language: java
jdk:
- oraclejdk8
before_install: git clone --depth 1 https://github.com/igniterealtime/ci-tooling.git
  target/ci-tooling
deploy:
  provider: script
  script: mvn deploy --settings target/ci-tooling/maven-settings-for-openfire-plugins.xml
  skip_cleanup: true
  on:
    all_branches: true
env:
  global:
  - secure: OOQi2JUrqZZ1ByFpiIm4QYXUUuIoOGRuY7SAmwVYnV9Gv4g0nsrJLLrd9yO5AjxnNJzvVMUx2dZGgBvfYdcUquyx8SJx9fQoO0LPAsf09P4/iojFllXDtJJIruAfW26NGSy6DpSIVUsjST6mshY0UD0kLdt3N9mAIoVzqbylwYpjQ/i35qwmctb5PXGDunYbKzlcGIgu49HDMGOpG3+OXM1ror+13wmoLB+Zloal39dv382YEYNOIeOBk2t4iUmu1Zs1qTIMqaaqjRuwqCdi0dT0HkBLA3hotDR76tm0KfNLgg7vcjcVYUKuMjR+lXJ2PW5bbwySl4hVhGM+rVx5uAeDhLTazjXu4aU8Sq5otAKRh/cw5mSbsH4JtTMOSVYXXrNLyTSLqBrNVdw2Whzbj8ZefBNSikAI2sF6SDOXNfl09dIw2yTilFSZgK8TZtIS6BvZ2tWXszOvd/AwhTHXVG8+K9Cc0RHyxRjpgO1nN9dnGq/Msvvn2r+2XGxfjY9vWFhb3OckzoxNZ267s4x9Vy09pE4jMaCsNmW3qrGNZQLT4grTs+/NnR4lK7KTCufGrmpYYuJ7cWCo/scielRcyXihznIPSwtplpHQjCYm7n8ANwJP1UUjGi2ZYoEpaNdZvXCAfPnE4XxQKipvyEGH0BgEWOZw8s02Ux7Ayzm++dQ=
  - secure: jP9znp47CrOPmgnXhGT5ttY9zoRT43/3ROzg36HEupsv1lyXPNuyrttVIHvU0DAaIH37/vLMHxoUc3bHC+zcPlWqV/2X+4qk8XJzlzeJGoLOLXCbKCZ9PqbTmueuW4HGzfj/cgSPGTWspwmQTqw4AuXD5l84pfu9jBh7Dqrct8CaFtOJ9vuyB1CcMtwcn6oxKKeAypCykEAGDxZjhTX2X2DmamPzzwws3C4RrRsLlDpJzbFTd4+BsXgF7T7kYWW2vt6dcFNT7+FAjnagt1muyFQ4aAaluwq9Fuv13QEFieaepDbT0YMYKYpAA5xXeotY2ItN8aAnGijGOtZQmQg8Skqd9QUb0M/kvhjaDe7k3AVcoDlVwl1+wDnzvdbHAoL4C7G0PqAITrFHLSBM6hBoO6qSCJLhbG646a6AM/RA+Xb36coHm/PKmM7hqxKS7z3W84souGDo8t/YU0gT53e8QLH+95rKdgggojvfWMDHcKFLEHWit33BqP9PeL+LjUMCvjqI6gPDxZhh2NQe0adAz6l3qNbSEtVEFGzppISjYGZJsFTkxK2/8rQzyD4S711b1CRm/OxoyXMVjlcqEgNHFp+yX16lSLp4RcoQx9hpcx4kPb+Vjy+yXV9cIzTeA8ULCFP8zoBWFkwPbVfgHUEdNDZB7T82opGFhQ32aoyBLSE=
